<?php
$labels = array();
$labels['password'] = 'Passwort';
$labels['changepasswd'] = 'Passwort ändern';
$labels['curpasswd'] = 'Altes Passwort:';
$labels['newpasswd'] = 'Neues Passwort:';
$labels['confpasswd'] = 'Neues Passwort bestätigen:';

$messages = array();
$messages['nopassword'] = 'Bitte geben Sie ein neues Passwort ein.';
$messages['nocurpassword'] = 'Bitte geben Sie Ihr altes Passwort ein.';
$messages['passwordincorrect'] = 'Das Passwort ist nicht richtig.';
$messages['passwordinconsistency'] = 'Das Passwort stimmt nich &uuml;berein. Bitte versuchen Sie es nochmal again.';
$messages['passwordminlength'] = 'Das Passwort ist zu kurz (Mindestlänge ist %d Zeichen).';
$messages['passwordchecknumber'] = 'Das Passwort muss mindestens eine Zahl enthalten.';
$messages['passwordchecklower'] = 'Das Passwort muss mindestens einen Kleinbuchstaben enthalten.';
$messages['passwordcheckupper'] = 'Das Passwort muss mindestens einen Großbuchstaben enthalten.';
$messages['passwordchecksymbol'] = 'Das Passwort muss mindestens ein Symbol enthalten.';

$messages['password_rules'] = 'Passwortregeln:';
$messages['password_rule_length'] = 'Mindestens %d Zeichen';
$messages['password_rule_upper'] = 'Mindestens 1 Gro&szlig;buchstabe';
$messages['password_rule_lower'] = 'Mindestens 1 Kleinbuchstabe';
$messages['password_rule_symbol'] = 'Mindestens 1 Sonderzeichen';
$messages['password_rule_number'] = 'Mindestens 1 Zahl';
?>